trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureCLI@2
    displayName: 'Install Azure CLI'
    inputs:
      azureSubscription: 'Visual Studio Enterprise Subscription(8377ac7f-7423-4f7a-909b-0eed6a86ec22)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash'

  - task: AzureCLI@2
    displayName: 'Create AKS Cluster'
    inputs:
      azureSubscription: 'Visual Studio Enterprise Subscription(8377ac7f-7423-4f7a-909b-0eed6a86ec22)'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az aks create --resource-group rg-glb-03 --name aksdemo3 --node-count 1 --node-vm-size Standard_D2ls_v5 --generate-ssh-keys'