trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - '*'

variables:
  - group: AKS_Cluster1_Variables
  - group: AKS_Cluster2_Variables

stages:
  - stage: Cluster1
    displayName: 'Deploy to Cluster 1'
    jobs:
      - job: Deployment
        displayName: 'Deploy to Cluster 1'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'Azure Login'
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(8377ac7f-7423-4f7a-909b-0eed6a86ec22)'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az aks get-credentials --resource-group $(Cluster1_ResourceGroup) --name $(Cluster1_ClusterName)'

          - script: |
              # Add your deployment commands for Cluster 1 here
            displayName: 'Deploy to Cluster 1'

  - stage: Cluster2
    displayName: 'Deploy to Cluster 2'
    jobs:
      - job: Deployment
        displayName: 'Deploy to Cluster 2'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            displayName: 'Azure Login'
            inputs:
              azureSubscription: 'Visual Studio Enterprise Subscription(8377ac7f-7423-4f7a-909b-0eed6a86ec22)'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: 'az aks get-credentials --resource-group $(Cluster2_ResourceGroup) --name $(Cluster2_ClusterName)'

          - script: |
              # Add your deployment commands for Cluster 2 here
            displayName: 'Deploy to Cluster 2'